'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import maplibregl from 'maplibre-gl';
import {Activity,CloudRain,Globe2,Search,TrendingUp,Users,Ship,Clock3,Plus,Minus,RotateCcw} from 'lucide-react';
type C={name:string;iso3:string;lat:number;lon:number}; type Q={id:string;mag:number;place:string;time:number;url?:string;coordinates:number[]};
const countries:C[]=[{name:'ประเทศไทย',iso3:'THA',lat:13.75,lon:100.5},{name:'จีน',iso3:'CHN',lat:35.9,lon:104.2},{name:'ญี่ปุ่น',iso3:'JPN',lat:36.2,lon:138.3},{name:'สหรัฐอเมริกา',iso3:'USA',lat:37.1,lon:-95.7},{name:'สหราชอาณาจักร',iso3:'GBR',lat:55.4,lon:-3.4},{name:'สิงคโปร์',iso3:'SGP',lat:1.35,lon:103.8},{name:'อินเดีย',iso3:'IND',lat:20.6,lon:79},{name:'ออสเตรเลีย',iso3:'AUS',lat:-25.3,lon:133.8},{name:'บราซิล',iso3:'BRA',lat:-14.2,lon:-51.9},{name:'เยอรมนี',iso3:'DEU',lat:51.2,lon:10.4}];
const fmt=(n:any)=>n==null?'—':Intl.NumberFormat('th-TH',{notation:'compact',maximumFractionDigits:1}).format(n);
export default function World(){
const mapRef=useRef<HTMLDivElement>(null), mapObj=useRef<any>(null), markers=useRef<any[]>([]);
const [country,setCountry]=useState(countries[0]),[quakes,setQuakes]=useState<Q[]>([]),[weather,setWeather]=useState<any>(null),[facts,setFacts]=useState<any>(null),[forecast,setForecast]=useState<any>(null),[layer,setLayer]=useState('ภัยพิบัติ'),[query,setQuery]=useState(''),[mapReady,setMapReady]=useState(false),[mapError,setMapError]=useState('');
useEffect(()=>{if(!mapRef.current||mapObj.current)return;try{const map=new maplibregl.Map({container:mapRef.current,style:'https://tiles.openfreemap.org/styles/liberty',center:[20,18],zoom:1.25,minZoom:1,maxZoom:10,attributionControl:true});map.addControl(new maplibregl.NavigationControl({showCompass:false}),'bottom-right');map.on('load',()=>{setMapReady(true);map.resize()});map.on('error',(e:any)=>{if(!map.loaded())setMapError('แผนที่ฐานโหลดไม่สำเร็จ กรุณาตรวจสอบอินเทอร์เน็ต')});mapObj.current={map,ml:maplibregl};const resize=()=>map.resize();window.addEventListener('resize',resize);const ro=new ResizeObserver(resize);ro.observe(mapRef.current);return()=>{ro.disconnect();window.removeEventListener('resize',resize);map.remove();mapObj.current=null}}catch(e){setMapError('ไม่สามารถเริ่มระบบแผนที่ได้')}} ,[]);
useEffect(()=>{let dead=false;Promise.all([fetch('/api/earthquakes',{cache:'no-store'}).then(r=>r.json()),fetch(`/api/weather?lat=${country.lat}&lon=${country.lon}`,{cache:'no-store'}).then(r=>r.json()),fetch(`/api/country?code=${country.iso3}`,{cache:'no-store'}).then(r=>r.json()),fetch(`/api/forecast?lat=${country.lat}&lon=${country.lon}`,{cache:'no-store'}).then(r=>r.json())]).then(([q,w,f,fc])=>{if(!dead){setQuakes(q.events||[]);setWeather(w);setFacts(f);setForecast(fc)}}).catch(()=>{});return()=>{dead=true}},[country]);
useEffect(()=>{if(!mapReady||!mapObj.current)return;markers.current.forEach(m=>m.remove());markers.current=[];const {map,ml}=mapObj.current;if(layer==='ภัยพิบัติ'){quakes.filter(q=>!query||q.place.toLowerCase().includes(query.toLowerCase())).slice(0,100).forEach(q=>{if(!q.coordinates)return;const el=document.createElement('button');el.className='mlquake '+(q.mag>=5?'major':'');el.title=`M ${q.mag} • ${q.place}`;el.innerHTML=`<i></i><span>M${Number(q.mag).toFixed(1)}</span>`;el.onclick=()=>{if(q.url)window.open(q.url,'_blank','noopener,noreferrer')};markers.current.push(new ml.Marker({element:el}).setLngLat([q.coordinates[0],q.coordinates[1]]).addTo(map))})}const selected=document.createElement('div');selected.className='selected-country';selected.innerHTML='<i></i>';markers.current.push(new ml.Marker({element:selected}).setLngLat([country.lon,country.lat]).addTo(map));},[mapReady,layer,quakes,query,country]);
function focus(c:C){setCountry(c);mapObj.current?.map?.flyTo({center:[c.lon,c.lat],zoom:4,duration:900})}
const hours=useMemo(()=>{const h=forecast?.hourly;if(!h?.time)return[];return h.time.slice(0,12).map((t:string,i:number)=>({t,temp:h.temperature_2m[i],rain:h.precipitation_probability[i],wind:h.wind_speed_10m[i]}))},[forecast]);
return <div className="worldpage"><header className="worldhead"><div><div className="eyebrow">WORLD EXPLORER / LIVE PUBLIC DATA</div><h1>แผนที่โลก</h1><p>สำรวจโลกจากพิกัดและข้อมูลต้นทางจริง • คลิกเหตุการณ์เพื่อเปิด USGS</p></div><div className="worldsearch"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาเหตุการณ์ USGS"/></div></header>
<div className="worldtoolbar"><div className="layerbuttons">{['ภัยพิบัติ','อากาศ','เศรษฐกิจ','การค้า'].map(x=><button key={x} className={layer===x?'on':''} onClick={()=>setLayer(x)}>{x}</button>)}</div><select value={country.iso3} onChange={e=>focus(countries.find(c=>c.iso3===e.target.value)||countries[0])}>{countries.map(c=><option key={c.iso3} value={c.iso3}>{c.name}</option>)}</select></div>
<section className="worldworkspace"><div className="mapframe"><div ref={mapRef} className="maplibrehost"/>{!mapReady&&!mapError&&<div className="maploading"><Globe2/>กำลังโหลดแผนที่จริง…</div>}{mapError&&<div className="maploading">{mapError}</div>}<div className="maphud"><b>DATOVA WORLD INTELLIGENCE</b><span>{layer==='ภัยพิบัติ'?quakes.length+' USGS events':'เลือก Layer: '+layer}</span></div><div className="mapchips">{countries.slice(0,6).map(c=><button key={c.iso3} className={c.iso3===country.iso3?'on':''} onClick={()=>focus(c)}>{c.name}</button>)}</div></div>
<aside className="countryrail"><div className="railcountry"><span>SELECTED COUNTRY</span><h2>{country.name}</h2><small>{country.iso3}</small></div><div className="countrymetric"><CloudRain/><div><span>อากาศปัจจุบัน</span><strong>{weather?.current?weather.current.temperature_2m+' °C':'—'}</strong><small>{weather?.current?`ความชื้น ${weather.current.relative_humidity_2m}% • ลม ${weather.current.wind_speed_10m} กม./ชม.`:'Open-Meteo'}</small></div></div><div className="countrymetric"><TrendingUp/><div><span>GDP</span><strong>{facts?.gdp?.value?'$'+fmt(facts.gdp.value):'—'}</strong><small>{facts?.gdp?.date?facts.gdp.date+' • World Bank':'—'}</small></div></div><div className="countrymetric"><Users/><div><span>ประชากร</span><strong>{fmt(facts?.population?.value)}</strong><small>{facts?.population?.date?facts.population.date+' • World Bank':'—'}</small></div></div><div className="countrymetric"><Ship/><div><span>Trade / GDP</span><strong>{facts?.tradePctGdp?.value!=null?facts.tradePctGdp.value.toFixed(1)+'%':'—'}</strong><small>{facts?.tradePctGdp?.date?facts.tradePctGdp.date+' • World Bank':'—'}</small></div></div></aside></section>
<section className="forecastbar"><div className="eventtitle"><CloudRain size={16}/><b>48H WEATHER • {country.name}</b><span>Open-Meteo • แสดง 12 ชั่วโมงแรก</span></div><div className="forecastscroll">{hours.map((h:any)=><div className="hour" key={h.t}><span>{new Date(h.t).toLocaleTimeString('th-TH',{hour:'2-digit',minute:'2-digit'})}</span><b>{h.temp}°</b><small>ฝน {h.rain??'—'}%</small><small>ลม {h.wind} km/h</small></div>)}</div></section>
<section className="eventstrip"><div className="eventtitle"><Activity size={16}/><b>LIVE EARTHQUAKE SIGNALS</b><span>{quakes.length} เหตุการณ์ • USGS 24 ชม.</span></div><div className="eventscroll">{quakes.filter(q=>!query||q.place.toLowerCase().includes(query.toLowerCase())).slice(0,12).map(q=><a className="eventchip" href={q.url} target="_blank" rel="noreferrer" key={q.id}><b>M {q.mag.toFixed(1)}</b><span>{q.place}</span><small><Clock3 size={11}/>{new Date(q.time).toLocaleTimeString('th-TH',{timeZone:'Asia/Bangkok'})}</small></a>)}</div></section>
<div className="datadisclaimer">ฐานแผนที่: © OpenStreetMap contributors • Rendering: MapLibre GL • เหตุการณ์: USGS • Weather: Open-Meteo • Country indicators: World Bank. แต่ละแหล่งอาจมีรอบอัปเดตต่างกัน</div></div>}