'use client';
import {useEffect,useMemo,useState} from 'react';
import {Activity,CloudRain,Globe2,Search,TrendingUp,Users,Ship,Clock3} from 'lucide-react';
type C={name:string;iso3:string;lat:number;lon:number};
type Q={id:string;mag:number;place:string;time:number;coordinates:number[]};
const countries:C[]=[{name:'ประเทศไทย',iso3:'THA',lat:13.75,lon:100.5},{name:'จีน',iso3:'CHN',lat:35.9,lon:104.2},{name:'ญี่ปุ่น',iso3:'JPN',lat:36.2,lon:138.3},{name:'สหรัฐอเมริกา',iso3:'USA',lat:37.1,lon:-95.7},{name:'สหราชอาณาจักร',iso3:'GBR',lat:55.4,lon:-3.4},{name:'สิงคโปร์',iso3:'SGP',lat:1.35,lon:103.8},{name:'อินเดีย',iso3:'IND',lat:20.6,lon:79},{name:'ออสเตรเลีย',iso3:'AUS',lat:-25.3,lon:133.8},{name:'บราซิล',iso3:'BRA',lat:-14.2,lon:-51.9},{name:'เยอรมนี',iso3:'DEU',lat:51.2,lon:10.4}];
const fmt=(n:number|null|undefined)=>n==null?'—':Intl.NumberFormat('th-TH',{notation:'compact',maximumFractionDigits:1}).format(n);
export default function World(){
const [country,setCountry]=useState(countries[0]),[quakes,setQuakes]=useState<Q[]>([]),[weather,setWeather]=useState<any>(null),[facts,setFacts]=useState<any>(null),[layer,setLayer]=useState('ภัยพิบัติ'),[query,setQuery]=useState('');
useEffect(()=>{let dead=false;Promise.all([fetch('/api/earthquakes').then(r=>r.json()),fetch(`/api/weather?lat=${country.lat}&lon=${country.lon}`).then(r=>r.json()),fetch(`/api/country?code=${country.iso3}`).then(r=>r.json())]).then(([q,w,f])=>{if(!dead){setQuakes(q.events||[]);setWeather(w);setFacts(f)}}).catch(()=>{});return()=>{dead=true}},[country]);
const shown=useMemo(()=>quakes.filter(q=>!query||q.place.toLowerCase().includes(query.toLowerCase())).slice(0,70),[quakes,query]);
const project=(lon:number,lat:number)=>({left:((lon+180)/360*100)+'%',top:((90-lat)/180*100)+'%'});
return <div className="worldpage"><header className="worldhead"><div><div className="eyebrow">WORLD EXPLORER / LIVE PUBLIC DATA</div><h1>แผนที่โลก</h1><p>สำรวจเหตุการณ์จริงบนโลก แล้วเจาะข้อมูลประเทศจากต้นทางสาธารณะ</p></div><div className="worldsearch"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="ค้นหาพื้นที่ในเหตุการณ์ USGS"/></div></header>
<div className="worldtoolbar"><div className="layerbuttons">{['ภัยพิบัติ','อากาศ','เศรษฐกิจ','การค้า'].map(x=><button key={x} className={layer===x?'on':''} onClick={()=>setLayer(x)}>{x}</button>)}</div><select value={country.iso3} onChange={e=>setCountry(countries.find(c=>c.iso3===e.target.value)||countries[0])}>{countries.map(c=><option key={c.iso3} value={c.iso3}>{c.name}</option>)}</select></div>
<section className="worldworkspace"><div className="realmap"><div className="mapgrid"/><div className="mapglow"/><div className="mapland northamerica"/><div className="mapland southamerica"/><div className="mapland europe"/><div className="mapland asia"/><div className="mapland africa"/><div className="mapland australia"/>
{layer==='ภัยพิบัติ'&&shown.map(q=>{const p=project(q.coordinates?.[0]||0,q.coordinates?.[1]||0);return <a key={q.id} className={'quakepoint '+(q.mag>=5?'major':'')} style={p} title={`M ${q.mag} • ${q.place}`}><i/><span>M{q.mag}</span></a>})}
<div className="mapwatermark"><Globe2 size={16}/> DATOVA WORLD INTELLIGENCE</div><div className="mapsource">USGS • Open-Meteo • World Bank</div></div>
<aside className="countryrail"><div className="railcountry"><span>SELECTED COUNTRY</span><h2>{country.name}</h2><small>{country.iso3}</small></div>
<div className="countrymetric"><CloudRain/><div><span>อากาศปัจจุบัน</span><strong>{weather?.current?weather.current.temperature_2m+' °C':'—'}</strong><small>{weather?.current?`ความชื้น ${weather.current.relative_humidity_2m}% • ลม ${weather.current.wind_speed_10m} กม./ชม.`:'Open-Meteo'}</small></div></div>
<div className="countrymetric"><TrendingUp/><div><span>GDP</span><strong>{facts?.gdp?.value?'$'+fmt(facts.gdp.value):'—'}</strong><small>{facts?.gdp?.date?facts.gdp.date+' • World Bank':'กำลังดึงข้อมูล'}</small></div></div>
<div className="countrymetric"><Users/><div><span>ประชากร</span><strong>{fmt(facts?.population?.value)}</strong><small>{facts?.population?.date?facts.population.date+' • World Bank':'—'}</small></div></div>
<div className="countrymetric"><Ship/><div><span>Trade / GDP</span><strong>{facts?.tradePctGdp?.value!=null?facts.tradePctGdp.value.toFixed(1)+'%':'—'}</strong><small>{facts?.tradePctGdp?.date?facts.tradePctGdp.date+' • World Bank':'—'}</small></div></div>
</aside></section>
<section className="eventstrip"><div className="eventtitle"><Activity size={16}/><b>LIVE EARTHQUAKE SIGNALS</b><span>{quakes.length} เหตุการณ์จาก feed 24 ชม.</span></div><div className="eventscroll">{shown.slice(0,12).map(q=><div className="eventchip" key={q.id}><b>M {q.mag.toFixed(1)}</b><span>{q.place}</span><small><Clock3 size={11}/>{new Date(q.time).toLocaleTimeString('th-TH',{timeZone:'Asia/Bangkok'})}</small></div>)}</div></section>
<div className="datadisclaimer">แผนที่ฐานในรอบนี้ยังเป็น schematic projection; จุดแผ่นดินไหวคำนวณจากพิกัดจริงของ USGS. ขั้นถัดไปจะเปลี่ยนฐานเป็นแผนที่ภูมิศาสตร์จริงพร้อม zoom/pan โดยไม่เปลี่ยน data pipeline.</div></div>}